name: Check Arduino Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        
      - name: Install Arduino AVR Core
        run: arduino-cli core install arduino:avr

      - name: Compile All Sketches
        run: |
          mkdir -p build
          find ./examples -name "*.ino" | while read sketch; do
            echo "Compiling $sketch..."
            arduino-cli compile --fqbn arduino:avr:uno "$sketch" --output-dir ./build --clean
          done
          
      - name: Upload Hex file
        uses: actions/upload-artifact@v4
        with:
          name: arduino-hex-file
          path: build/*.hex
